### ISSUE TITLE
Headless test instability with Chrome 64

### ISSUE THREAD

**Issue by andrewhao** [carbonfive/shimmer#13]
Chrome 64 was released on Jan 25. This caused our headless tests to suddenly become much more unstable:

```
3) querying elements #find does not find elements that are hidden
     Failure/Error:
       expect {
         find(".should-be-hidden")
       }.to raise_error(Capybara::ElementNotFound)

       expected Capybara::ElementNotFound, got #<NoMethodError: undefined method `flatten' for nil:NilClass> with backtrace:
         # ./lib/shimmer/finder.rb:52:in `nodes_from_property_array'
         # ./lib/shimmer/finder.rb:32:in `find_css'
         # ./spec/features/querying_elements_spec.rb:39:in `block (4 levels) in <top (required)>'
         # ./spec/features/querying_elements_spec.rb:38:in `block (3 levels) in <top (required)>'
     # ./spec/features/querying_elements_spec.rb:38:in `block (3 levels) in <top (required)>'
...
```

Headed tests still seem to be fine, though.

**Comment by andrewhao** [comment]
Addressed with #10
